// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteMVC.Data;

namespace RestauranteMVC.Migrations
{
    [DbContext(typeof(RestauranteMVCContext))]
    partial class RestauranteMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RestauranteMVC.Models.Favorecidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<string>("Endereco");

                    b.Property<string>("Nome");

                    b.Property<int>("Nr");

                    b.HasKey("Id");

                    b.ToTable("Favorecidos");
                });
#pragma warning restore 612, 618
        }
    }
}
